"""Add Bio-Intelligence tables

Revision ID: 2af409918009
Revises: 
Create Date: 2026-05-25 09:18:21.499077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2af409918009'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biological_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('species_name', sa.String(), nullable=True),
    sa.Column('compounds', sa.JSON(), nullable=True),
    sa.Column('drug_classes', sa.JSON(), nullable=True),
    sa.Column('medicinal_uses', sa.JSON(), nullable=True),
    sa.Column('agricultural_uses', sa.JSON(), nullable=True),
    sa.Column('cosmetic_uses', sa.JSON(), nullable=True),
    sa.Column('toxicity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biological_entities_domain'), 'biological_entities', ['domain'], unique=False)
    op.create_index(op.f('ix_biological_entities_species_name'), 'biological_entities', ['species_name'], unique=True)
    op.create_table('bio_prediction_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('species_predicted', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('farmer_report', sa.JSON(), nullable=True),
    sa.Column('scientist_report', sa.JSON(), nullable=True),
    sa.Column('knowledge_version', sa.String(), nullable=True),
    sa.Column('embedding_version', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_prediction_history_user_id'), 'bio_prediction_history', ['user_id'], unique=False)
    op.drop_index(op.f('ix_treatment_tracks_detection_id'), table_name='treatment_tracks')
    op.drop_index(op.f('ix_treatment_tracks_id'), table_name='treatment_tracks')
    op.drop_table('treatment_tracks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_tracks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('detection_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('treatment_applied', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recovery_progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['disease_detections.id'], name=op.f('treatment_tracks_detection_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('treatment_tracks_pkey'))
    )
    op.create_index(op.f('ix_treatment_tracks_id'), 'treatment_tracks', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_tracks_detection_id'), 'treatment_tracks', ['detection_id'], unique=False)
    op.drop_index(op.f('ix_bio_prediction_history_user_id'), table_name='bio_prediction_history')
    op.drop_table('bio_prediction_history')
    op.drop_index(op.f('ix_biological_entities_species_name'), table_name='biological_entities')
    op.drop_index(op.f('ix_biological_entities_domain'), table_name='biological_entities')
    op.drop_table('biological_entities')
    # ### end Alembic commands ###
